74 commoditymarketinfoview optimization
eddb2-0/EDDB-2.0-backend pull request #123
Opened 2023-09-30 14:49 UTC by pveeckhout

2023-10-01 23:16 UTC, Daniel-J-Mason requested changes
Additionally need to add a unique key to commodity name table to allow ON CONFLICT (name) to trigger correctly.

2023-10-01 23:16 UTC, Daniel-J-Mason commented on exploration-module/src/main/java/io/edpn/backend/exploration/adapter/persistence/MybatisSystemRepository.java
Worth considering fully dropping coordinates.

We can create some debugging views which extract x, y, z from geom so we can view them internally as needed but not referenced by the api.

2023-10-01 23:16 UTC, Daniel-J-Mason commented on trade-module/src/main/java/io/edpn/backend/trade/adapter/config/ServiceConfig.java
> +            CreateOrLoadSystemPort loadOrCreateSystemByNamePort,
rename variable to match class

2023-10-01 23:16 UTC, Daniel-J-Mason commented on trade-module/src/main/java/io/edpn/backend/trade/adapter/config/ServiceConfig.java
> +            CreateOrLoadStationPort loadOrCreateBySystemAndStationNamePort,
rename variable to match class

2023-10-01 23:16 UTC, Daniel-J-Mason commented on trade-module/src/main/java/io/edpn/backend/trade/adapter/config/ServiceConfig.java
> +            CreateOrLoadCommodityPort loadOrCreateCommodityByNamePort,
rename variable to match class

2023-10-01 23:16 UTC, Daniel-J-Mason commented on trade-module/src/main/java/io/edpn/backend/trade/adapter/persistence/repository/MybatisCommodityRepository.java
> +            "ON CONFLICT name",
add parenthesis:

ON CONFLICT (name)

2023-10-01 23:16 UTC, Daniel-J-Mason commented on trade-module/src/main/resources/db/trademodule/changelog/drop_validated_market_datum_view.xml
Have we defined our inflection point yet?

Previously discussed keeping liquibase trimmed out until we decided to enter a permanent rolling db development phase

2023-10-01 23:16 UTC, Daniel-J-Mason commented on trade-module/src/main/java/io/edpn/backend/trade/application/port/outgoing/marketdatum/CreateWhenNotExistsLatestMarketDatumPort.java
> +    void createWhenNotExists(UUID stationId, MarketDatum marketDatum);
Rename port to something like:
createOrUpdateExisting

This differs fundamentally from how the full MarketDatum table operates and this method should indicate that.

2023-10-02 07:52 UTC, pveeckhout commented on trade-module/src/main/resources/db/trademodule/changelog/drop_validated_market_datum_view.xml
generally I find it good to practise 
at this point I won't chastise anyone for drop and recreate, but ... we will need to do rolling updates in the future, might as well get used to the flow

2023-10-02 07:55 UTC, pveeckhout commented on exploration-module/src/main/java/io/edpn/backend/exploration/adapter/persistence/MybatisSystemRepository.java
done

2023-10-03 10:42 UTC, Daniel-J-Mason approved these changes

2023-10-03 10:55 UTC, merged